### PR TITLE
Bug/173 monte carlo inverse code fixes

### PR DESCRIPTION
**Pull request by hayakawa16**
I think this is ready for review.  Please see issues page for more description of what was changed.

### CODE REVIEW

**Review by janakarana — APPROVED** [review]
Everything looks good. Thanks.

**Comment by hayakawa16** [comment]
Thanks for your review @janakarana!!

**Comment by hayakawa16** [comment]
I added sample output plots to the wiki page:
https://github.com/VirtualPhotonics/Vts.MonteCarlo/wiki/MCCL-Inverse-Solutions
Let me know what you think.  Thanks!

**Review by parsanam92 — APPROVED** [review]

**Review by lmalenfant — APPROVED** [review]
Looks good to me!

**Pull request merged**
