### PR TITLE
Publish documentation to GitHub Pages

### LINKED ISSUE #92: Publish static web hosted documentation to Github Pages
### Discussed in https://github.com/VirtualPhotonics/VTS/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **dcuccia** August  3, 2023</sup>
I was able to quickly validate that [DocFx](https://dotnet.github.io/docfx/index.html) can create static website docs like this:

image

More info [here](https://dotnet.github.io/docfx/docs/basic-concepts.html), and [here](https://dotnet.github.io/docfx/index.html#publish-to-github-pages) is how to build from GitHub Actions and host on GitHub Pages.

Is this something we could consider? Would be my personal preference for referencing docs, versus downloading a help file locally.

Repro of the steps I took to build and run locally are as follows:

1. Install DocFx as a global tool:
```
dotnet tool install -g docfx
```
3. Navigate to the VTS root code directory and initialize with "quiet" mode:
```
docfx init -q
```
4. Update the auto-generated docfx.json file with the following "src" subsection:
```json
"src": [
        {
          "files": [
            "Vts/Vts.csproj",
            "Vts.MonteCarlo.CommandLineApplication/Vts.MonteCarlo.CommandLineApplication.csproj",
            "Vts.MonteCarlo.PostProcessor/Vts.MonteCarlo.PostProcessor.csproj"
          ],
          "src": "../src"
        }
      ],
```
5. Generate the metadata from the targeted Vts libraries:
```
docfx metadata docfx_project/docfx.json
```
6. Build the site and run the tool on localhost:8080:
```
docfx docfx_project\docfx.json --serve
```

</div>

### PR DESCRIPTION
**Pull request by dcuccia**
This should add DocFx metadata and a GitHub action that will publish an update to the documentation a) on demand ("workflow dispatch") and b) upon any commit to main (master). This will keep the documentation in sync with the code changes. I think all we need to do is enable Pages on the main site. Note: recommend "squashing" the commits when accepting and merging the PR, the individual commits aren't really helpful.

Fixes #92

### CODE REVIEW

**Comment by dcuccia** [comment]
@lmalenfant  think you can checkout and edit the code with the GitHub CLI with `gh pr checkout 93` and push any edits you want.

**Comment by dcuccia** [comment]
Oh, I assumed those would be wiped with the squash. Maybe not? Would be great to know how to do this properly, when there are lots of files involved, otherwise it might be a lot of work for the maintainer. It's probably best practice for the PR submitter to manage this complexity, I just don't have any experience with it.

**Comment by dcuccia** [comment]
I see now what you meant by pull changes and add them. Thought you'd be going through the PR file by file, but realize you can pull, make a copy, checkout new branch, paste. I can definitely do that and issue a new PR, if you'd like.

**Comment by lmalenfant** [comment]
Yes I was able to pull your code and just update the files. It's working! :)
https://virtualphotonics.github.io/VTS/

Thank you for this, it's awesome! It needs a little more work but I can fix it on the branch and then switch it to master.

**Comment by dcuccia** [comment]
Awesome! You're welcome. :)

**Comment by lmalenfant** [comment]
I am closing this PR, I will create another one with the branch that I created.

**Pull request closed without merging**
