### PR TITLE
Create build.yaml

### PR DESCRIPTION
**Pull request by lmalenfant**

### CODE REVIEW

**Comment by lmalenfant** [comment]
I was able to get this pipeline working on the VTS repo (it took me a while!) This pipeline does build, test and code coverage. The code coverage and test are in the same command but I think they still work as expected. This means now that every time we create a PR, it will run the checks.

**Review by hayakawa16 — APPROVED** [review]
Nice success!

**Comment by dcuccia** [comment]
Would like to review but it will take some time (sorry!)

**Comment by lmalenfant** [comment]
@dcuccia I added you more for visibility than to review, I know you're busy right now.

Feel free to take a look later and if you have suggestions we can make modifications then.

**Pull request merged**
